wget "https://jsonplaceholder.typicode.com/posts" -O "data/posts.json"
wget "https://jsonplaceholder.typicode.com/comments" -O "data/comments.json"
wget "https://jsonplaceholder.typicode.com/albums" -O "data/albums.json"
wget "https://jsonplaceholder.typicode.com/photos" -O "data/photos.json"
wget "https://jsonplaceholder.typicode.com/todos" -O "data/todos.json"
wget "https://jsonplaceholder.typicode.com/users" -O "data/users.json"
