name: 'Production'

on:
  push:
    branches:
      - master

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: 'Clone repository'
        uses: actions/checkout@v2
      - name: 'Deploy to remote server'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            source $NVM_DIR/nvm.sh
            cd /var/www/json-placeholder
            git pull
            yarn
            yarn build
            pm2 restart json-placeholder-prd
