name: 'Staging'

on:
  push:
    branches:
      - '!master'

jobs:
  build:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: 'Clone repository'
        uses: actions/checkout@v2
      - name: 'Deploy to remote server'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /var/www/json-placeholder-staging
            git checkout ${{ GITHUB_REF_NAME }}
            git pull
            yarn
            yarn build
            pm2 restart json-placeholder-staging
